services:
  mongodb:
    image: mongo:6
    container_name: my-mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - my-backend-net
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redisdb:
    image: redis:7.2-alpine
    command: redis-server --maxmemory 100mb --maxmemory-policy volatile-lfu
    container_name: my-redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}" 
    networks:
      - my-backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    container_name: my-cassandra-container
    restart: always
    ports:
      - "9042:9042"
    networks:
      - my-backend-net
    volumes:
      - cassandra-data:/var/lib/cassandra
      - ./back/src/scripts/init-cassandra.sh:/init-cassandra.sh
    environment:
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESC KEYSPACES'"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    networks:
      - my-backend-net
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./back/src/scripts/init-cassandra.sh:/init-cassandra.sh
    command: bash /init-cassandra.sh
    restart: "no"

  backend:
    build: 
      context: ./back
      dockerfile: dockerfile.dev
    container_name: my-backend-container
    restart: always
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" 
    networks:
      - my-backend-net
    depends_on:
      cassandra:
        condition: service_healthy
      mongodb:
        condition: service_started
      redisdb:
        condition: service_started
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/news"]
      interval: 30s
      timeout: 10s
      retries: 3
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: my-frontend-container
    restart: always
    ports:
      - "8080:80"
    networks:
      - my-backend-net
    depends_on:
      - backend
    volumes:
      - ./front:/usr/share/nginx/html:ro

networks:
  my-backend-net:
    driver: bridge

volumes:
  mongodb:
  redis-data:
  cassandra-data: