services:
  mongodb:
    image: mongo:6
    container_name: my-mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    networks:
      - my-backend-net
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redisdb:
    image: redis:7.2-alpine
    command: redis-server --maxmemory 100mb --maxmemory-policy volatile-lfu
    container_name: my-redis-container
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}" 
    networks:
      - my-backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    container_name: my-cassandra-container
    restart: always
    ports:
      - "9042:9042"
    networks:
      - my-backend-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_START_RPC=true

  backend:
    build: 
      context: ./back
      dockerfile: dockerfile
    container_name: my-backend-container
    restart: always
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}" 
    networks:
      - my-backend-net
    depends_on:
      - cassandra
      - mongodb
      - redisdb
  frontend:
    build:
      context: ./front
      dockerfile: dockerfile
    container_name: my-frontend-container
    restart: always
    ports:
      - "8080:80"
    networks:
      - my-backend-net
    depends_on:
      - backend

networks:
  my-backend-net:
    driver: bridge

volumes:
  mongodb:
  cassandra-data: